#include "util.h"

#ifdef _WIN32
    void util::gotoxy(int x, int y) {
        static HANDLE handle = NULL;
        if(!handle) {
            handle = GetStdHandle(STD_OUTPUT_HANDLE);
        }
        COORD coord = { x, y };
        SetConsoleCursorPosition(handle, coord);
    }
#else
char getch() {
    char buf = 0;
    struct termios old = {0};
    if (tcgetattr(0, &old) < 0)
        perror("tcsetattr()");
    old.c_lflag &= ~ICANON;
    old.c_lflag &= ~ECHO;
    old.c_cc[VMIN] = 1;
    old.c_cc[VTIME] = 0;
    if (tcsetattr(0, TCSANOW, &old) < 0)
        perror("tcsetattr ICANON");
    if (read(0, &buf, 1) < 0)
        perror("read()");
    old.c_lflag |= ICANON;
    old.c_lflag |= ECHO;
    if (tcsetattr(0, TCSADRAIN, &old) < 0)
        perror("tcsetattr ~ICANON");
    return (buf);
}
    void util::gotoxy(int x, int y) {
        printf("%c[%d;%df",0x1B,y,x);
    }
#endif


void util::getchar(char &c) {
#ifdef _WIN32
	c = _getch();
#else
    c = getch();
#endif
}

int util::random(int a, int b) {
    /* initialize random seed: */
    std::random_device rd;  // Will be used to obtain a seed for the random number engine
    std::mt19937 gen(rd()); // Standard mersenne_twister_engine seeded with rd()
    // Use dis to transform the random unsigned int generated by gen into an int in [a, b]
    std::uniform_int_distribution<> dis(a, b);
    return dis(gen);
}

void util::sleep(int miliseconds) {
    std::this_thread::sleep_for(std::chrono::milliseconds(miliseconds));
}

void util::clear() {
#ifdef _WIN32
	system("cls");
#else
	system("clear");
#endif // _WIN32
}

void util::remove(int x, int y) {
	gotoxy(x, y);
	std::cout << " ";
}

